# Generated by Django 6.1 on 2026-08-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_user_email_verified_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
    ]
