# Generated by Django 6.1 on 2026-08-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_user_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationcode',
            name='user',
        ),
        migrations.AddField(
            model_name='activationcode',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
